---
production:
  cloud_name: ENV['CLOUD']
  api_key: ENV['KEY']
  api_secret: ENV['SECRET']
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: restaurantapp
  api_key: '714446869925478'
  api_secret: Z_3e5mQFZp4RQ4x9DuOUrw10eBw
  enhance_image_tag: true
  static_file_support: false
